### ISSUE TITLE
Expected fields in billingAddress and shippingAddress

### ISSUE THREAD

**Issue by Kent-N** [quantity-digital/commerce-economic#2]
Hi

The plugin expects the fields `firstName` and `lastName` to be set on orders. Commerce however, also has a `fullName` field that is intended to (optionally) replace the former two. With only `fullName` set, the order never gets sent to E-conomic and this error is found in economic.log

`{"message":"Validation failed. 1 error found.","errorCode":"E04300","developerHint":"Inspect validation errors and correct your request.","logId":"67c0f3bd336b10b9-CPH","httpStatusCode":400,"errors":{"name":{"errors":[{"propertyName":"name","errorMessage":"Property name is null or empty.","errorCode":"E04041","inputValue":" ","developerHint":"Property name must not be null or empty."}]}},"logTime":"2021-08-09T14:22:49","errorCount":1}`

**Comment by CMeldgaard** [comment]
Fixed in [1.1.3](https://github.com/quantity-digital/commerce-economic/releases/tag/1.1.3)
